config/routes.rb
Pets::Application.routes.draw do

  resources :pets, :only => [:index, :show]
  root :to => 'pets#index'

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  def self.search(zip)
    if zip
      results = where(:zip => zip)
    else
      results = self.limit(200)
    end
    self.alternate_animals(results)
  end

  def self.alternate_animals(results)
    return_values = []
    dogs = []
    cats = []

    results.each do |animal|
      if animal.species == 'dog'
        dogs << animal
      elsif animal.species == 'cat'
        cats << animal
      end
    end

    (0..dogs.length).each do
      return_values << dogs.shift if dogs.count > 0
      return_values << cats.shift if cats.count > 0
    end
    [return_values, cats].flatten
  end

  def self.locations_with_pets
    zips = Pet.select(:zip).group(:zip).map(&:zip)
    Rails.logger.debug("zips" + zips.inspect)
    Zip.select([:zip, :city, :state]).where(:zip => zips).group(:zip).group(:city).group(:state)
  end


end

app/models/petfinder_connector.rb
class PetfinderConnector
  attr_accessor :zip, :animal

  def initialize
    @page = 1
    @type = 'animals'
    @limit = 100
    @client = Petfinder::Client.new
  end

  def find_pets
    if zip && animal
      pets = @client.find_pets(animal, zip)
      pets.each do |pet|
        pet_data = transform(pet)
        Pet.create(pet_data) if Pet.where(:remote_id => pet_data[:remote_id], :provider => pet_data[:provider]).empty?
      end
    end
  end

  def transform(data)
    {
      :provider => 'petfinder',
      :name => data.name,
      :species => data.animal,
      :breed => data.breeds.join(' '),
      :gender => data.sex,
      :photo => data.pictures.first.to_s, #transform to 235 x 230
      :zip => zip_from_result(data),
      :remote_id => data.id,
      :description => data.description,
      :age => data.age,
      :contact_email => contact_email(data)
    }
  end

  def shelter(data)
    @shelter ||= @client.shelter(data.shelter_id)
  end

  def zip_from_result(data)
    shelter(data)
    if @shelter
      @shelter.zip
    end
  rescue => e
    puts e
    #do nothing
  end

  def contact_email(data)
    shelter(data)
    if @shelter

    end
  end


end

app/models/requester.rb
class Requester
  attr_accessor :page, :limit

  include HTTParty
   parser(
    Proc.new do |body, _|
      Crack::XML.parse(body)
    end
  )
  debug_output $stderr

  def initialize(connector)
    @connector = connector
    self.class.base_uri(@connector.url)
  end

  def options
    {
      :limit => @limit || 100,
      :page => @page || 1
    }
  end

  def make_request
    data = self.class.get('/rest/', :timeout => 100, :query => @connector.url_params(options))
    parse_response(data)
  rescue Timeout
      make_request
  end

  def parse_response(data)
    data["pets"]["pet"].each do |pet|
      to_model(pet)
    end
  end

  def to_model(data)
    attributes = @connector.transform(data)
    Pet.create(attributes) if Pet.where(:provider => attributes[:provider], :remote_id => attributes[:remote_id]).empty?
  end
end

app/models/rescuegroup_connector.rb
class RescuegroupConnector

  def initialize
    @page = 1
    @type = 'animals'
    @limit = 100
  end

  def url_params(options = {})
    params = {}
    params[:key] = key
    params[:type] =  type(options[:type])
    params[:limit] = limit(options[:limit])
    params[:startPage] = page(options[:page])
    params
  end

  def url
    'http://api.rescuegroups.org/'
  end

  def key
    'RgKK5PGU'
  end

  def type(type = nil)
    @type = type if type
    @type
  end

  def limit(limit = nil)
    @limit = limit if limit
    @limit
  end

  def page(page = nil)
    @page = page if page
    @page
  end

  def transform(data)
    {
      :provider => 'rescuegroup',
      :name => data["name"],
      :species => data["species"].downcase,
      :breed => data["breed"],
      :gender => data["sex"],
      :photo => data["pic1"], #transform to 235 x 230
      :zip => data["locationZipcode"],
      :remote_id => data["animalID"],
      :kill_date =>data["killDate"] ,
      :kill_reason => data["killReason"],
      :description => data["description"],
      :click_url => data["petURL"],
      :age => data["age"],
      :remote_id => data["animalID"],
      :contact_email => data["contactEmail"],
    }
  end
end

app/models/runner.rb
class Runner
  def initialize(function, page = nil)
    @function = function
    @page = page
  end

  def run_rescue_group(page)
    requester = Requester.new(RescuegroupConnector.new)
    requester.page = page
    requester.limit = 100
    requester.make_request
  end

  def run_petfinder(page = nil)
    connector = PetfinderConnector.new
    Zip.select(:zip).group(:zip).each do |zip|
      %w(dog cat).each do |animal|
        connector.animal = animal
        connector.zip = zip.zip
        connector.find_pets
      end
    end
  end

  def perform
    if @page
      send(@function.to_sym, @page.to_i)
    else
      send(@function)
    end
  end
end

app/models/zip.rb
class Zip < ActiveRecord::Base
  set_table_name :zip
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  respond_to :html, :json

  def index
    @pets = Pet.search(params[:zip])
    if @pets.count > 0
      respond_with(@pets)
    else
      @locations = Pet.locations_with_pets
    end
  end

  def show
    @pet = Pet.find(params[:id])
    respond_with(@pet)
  end

private

  def petfinder
    @petfinder = Petfinder::Client.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pets</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pets/index.html.haml
#doggy-bag
  .doggy-bag-content
    .options
      .close
      .reset
    .items
      %h1
        You haven't added any buddies yet.
.search-bar
  %h1 Dogs in San Francisco, CA
  =form_tag pets_path, :method => :get do
    =text_field_tag('zip',nil, :placeholder => 'Enter your zip code')
    =submit_tag('Change location')
  .drop-zone.droppable
.hero-section
  .content
    .show-doggy-bag
    .logo
    %h1.main-heading
      Scruffy
      &nbsp;&nbsp;
      %span.cat-icon
      Buddy
    .form
      =form_tag pets_path, :method => :get do
        =text_field_tag('zip',nil, :placeholder => 'Enter your zip code')
        =submit_tag('Find A Pal')
#options.wrapper.clearfix
  .options
    %ul.clearfix
      %li#cat
        I
        %span.heart
        Cats
      %li#dog
        I
        %span.heart
        Dogs
  .blog-out
    Blog out with your dog out
#blog
  .next
  .prev
  .scrollable
    .items
      .post
        .image
          %img{:src => "http://images.dailydawdle.com/animals-in-sombreros8.jpg"}
        .content
          .pad
            %h2
              ¡ 20 Animals in Sombreros!
            %p
              It’s Cinco De Mayo, ya’ll… and what does that mean for us here at ScruffyBuddy? Animals. In. Sombreros.
      .post
        .image
          %img{:src => "http://us.123rf.com/400wm/400/400/kellyrichardsonfl/kellyrichardsonfl1011/kellyrichardsonfl101100180/8296986-cinco-de-mayo-partying-yellow-labrador-retriever-wearing-a-red-blue-natural-woven-sombrero-hat-isola.jpg"}
        .content
          .pad
            %h2
              5 Ways to Prepare for a New Pet
            %p
              Here at ScruffyBuddy we’re all about 2 things. Finding you a new pet, and showing you pictures of other people’s pets. We do plenty of the first (and the latter, really) but once in a while we find it’s time for a serious note.
            %p
              Adopting a new pet is no laughing matter, and while it may seem all fun and games there are certain things you should do to prepare yourself for little Lupo or Ludacris.
      .post
        .image
          %img{:src => "http://img0.etsystatic.com/il_570xN.303492036.jpg"}
        .content
          .pad
            %h2
              10 Bizarre Cat Paintings found on Etsy
            %p
              One with wine in a chalice, the other with a pimp stick. Me-ow. Also, there is an uncomfortable amount of results when one searches “vampire cats” on Etsy, btw.
              
  .nav
-if @pets.empty?
  #locations.wrapper.clearfix
    -@locations.each do |location|
      %a{:href => "?zip=#{location.zip}"}
        = "#{location.city}, #{location.state}"
-else
#pets.wrapper.clearfix
  - @pets.each do |pet|
    -if pet.photo?
      %div{:class => "container pet draggable #{pet.species}"}
        .card
          .face.front
            .filter
            .image-cropper
              = image_tag(pet.photo)
            %p
              = pet.name
          .face.back
            .content
              .thumb
                = image_tag(pet.photo)
              .favicon
              %a{:href => "#{pet.click_url}"}
                %span.click-off
              %p.desc
                = truncate(strip_tags(pet.description), :length => 150)
:javascript
  $(function(){
    if(!($.browser.webkit)){
      window.location = "http://img42.imageshack.us/img42/561/218catplayingelectricgu.gif";
    };

    $.each($('.pet'), function(){
      var amount = randomFromTo(-10, 10);
      $(this).css({'-webkit-transform':'rotate('+amount+'deg)'});
    })
    function randomFromTo(from, to){
       return Math.floor(Math.random() * (to - from + 1) + from);
    }

    $(window).scroll(function(){
     if($(window).scrollTop() > 300){
      $('.search-bar').fadeIn('fast');
     }else{
      $('.search-bar').fadeOut('fast');
     }
    });

    $('.options li').click(function(){
      var sibling = $(this).siblings('li').addClass('strike');
      $(this).removeClass('strike');
      var hide = sibling.attr('id');
      $('#pets .' + hide).addClass('hidden');
      $('#pets .' + $(this).attr('id')).removeClass('hidden');
    });

    $('.drop-zone, .show-doggy-bag').click(function(){
        $('#doggy-bag').animate({'top' : '0px'}, 300);
      }
    );
    $('#doggy-bag .close').click(function(){
      $('#doggy-bag').animate({'top' : '-400px'}, 300);
    });
    $('#doggy-bag .reset').click(function(){
      $('#doggy-bag .pet').remove();
      $('.items h1').removeClass('hidden');
    });

    $( ".draggable" ).draggable({
      revert: 'invalid',
      scroll: false
    });
    $( ".droppable" ).droppable({
        tolerance: 'touch',
        over: function(event, ui){
          $('.drop-zone').toggleClass('hovered');
          if($('#doggy-bag .items').children().length < 3){
            ui.draggable.toggleClass('semi-transparent');
          }
        },
        drop: function( event, ui ) {
          if(!($('.items h1').hasClass('hidden'))){
           $('.items h1').addClass('hidden');
          }
          $('.drop-zone').toggleClass('hovered');
          if($('#doggy-bag .items').children().length !== 4){
            $(ui.draggable).attr('style', '').removeClass('semi-transparent');
            $('#doggy-bag .items').append(ui.draggable);
          }
          else{
            $( '.draggable' ).draggable( "option", "revert", true );
          }
        }
    });

    $('#pets .favicon').click(function(){
      if(!($('.items h1').hasClass('hidden'))){
       $('.items h1').addClass('hidden');
      }
      var pet = $(this).closest('.pet');
      if(($('#doggy-bag .items').children().length !== 4) && (!$(this).hasClass('faved'))){
        $(this).addClass('faved');
        pet.clone().attr('style', '').appendTo('#doggy-bag .items');
      }
    });

    $('.scrollable').scrollable({
      circular:true
    });

    $('.blog-out').click(function(){
      $('#blog').show();
      $('.scrollable').animate({'height':'400px'}, 'fast');
    });

  });//en dom ready

app/views/pets/show.html.haml
%h1 Pets#show
%p Find me in app/views/pets/show.html.haml